export const SIGNED_IN = 'SIGNED_IN';
export const SET_GOALS = 'SET_GOALS';
export const SET_REMOVED_GOALS = 'SET_REMOVED_GOALS';
export const DELETED_GOALS = 'DELETED_GOALS';
export const DELETE_REMOVED_GOALS = 'DELETE_REMOVED_GOALS';
export const DELETE_ALL = 'DELETE_ALL';
